<article class="module width_full">
<header><h3>{$GLOBAL.website.name}</h3></header>
<div class="module_content">
<table width="100%">
<tbody>
<p>This Pool is running <a href="https://github.com/TheSerapher/php-mpos">MPOS</a> created by TheSerapher aka Sebastian Grewe.</p>

Below is a standard FAQ.
<ul>
<li><b><i>Q: When will I get paid?</b></i></li>
<li>A: This depends on the pools payout System. MPOS Support three different systems defined below.</li><br>
<b>* Proportional (Prop)</b> - The block reward is distributed among miners in proportion to the number of shares they submitted in a roun$
<br>
<b>* Pay Per Last N Shares (PPLNS)</b> - Block rewards are distributed among the last shares, disregarding round boundaries. In the accura$
<br>
<b>* Pay Per Share (PPS)</b> - Each share receives a fixed reward known in advance. This is the ultimate low- variance, low-maturity simpl$
<br>
<li><b><i>Q: What is a Orphan Block?</b></i></li>
<li>A: Coins generated by a block will not be available to you right away. They will take some time to be confirmed by the entire network $
<br>
<li><b><i>Q: What is a share?</b></i></li>
<li>A: Finding blocks is not an easy task. Since it would take a really long time on some coins, finding a block is broken down into share$
<br><br>
On the server side, each share is checked against the coin daemon (a server side wallet with more features) if it is indeed a valid block $
<br><br>
Keep in mind: shares are not blocks! Shares are part of a block and will count towards the block payout!
<br><br>
At times, you will see shares being rejected by the pool. This can happen if you try to send an outdated share right after a block was fou$
<br><br>
If you are seeing reject all the time, then something isn’t working right on your end. You may also notice that your hashrate on the pool $
<br>
<li><b><i>Q: I am having problems connecting to the pool.</b></i></li>
<li>A: Double check your settings against our <a href="/index.php?page=gettingstarted">getting started page.</a></li>
</ul>

</tbody>
</table>
</div>
</article>

